
<?php if ($this->msg): ?>
<div class="wrap">
	<h2 id="add-new-user"><?php echo $this->msg?></h2>
</div>
<?php endif;?>
<div class="wrap">
	<h2 id="add-new-user">Add new Client <a href="?page=Client" class="add-new-h2">List</a></h2>
	
	<p>Add a new client.</p>
	<form action="?page=Client&action=add&noheader=true" method="post" name="createclient" id="createclient" class="validate" novalidate="novalidate">
		<?php echo $form->formInput($form->getElement('id'));?>
		<table class="form-table">
			<tbody>
				<tr class="form-field form-required">
					<th scope="row">
						<?php echo $form->formLabel($form->getElement('name'));?>
					</th>
					<td>
						<?php echo $form->formInput($form->getElement('name'));?>
						<?php echo $form->errorMsg($form->getElement('name'));?>
					</td>
				</tr>
				<tr class="form-field form-required">
					<th scope="row">
						<?php echo $form->formLabel($form->getElement('email'));?>
					</th>
					<td>
						<?php echo $form->formInput($form->getElement('email'));?>
						<?php echo $form->errorMsg($form->getElement('email'));?>
					</td>
					
				</tr>
				<tr class="form-field">
					<th scope="row">
						<?php echo $form->formLabel($form->getElement('fone'));?>
					</th>
					<td>
						<?php echo $form->formInput($form->getElement('fone'));?>
						<?php echo $form->errorMsg($form->getElement('fone'));?>
					</td>

				</tr>
			</tbody>
		</table>
	
	
		<p class="submit">
			<input type="submit" name="addClient" id="addClient" class="button button-primary" value="Add new client">
		</p>
	</form>
</div>



