<div class="wrap">
	<h2 id="add-new-user">Edit Client <a href="?page=Client" class="add-new-h2">List</a></h2>
	
	<p>Edit client.</p>
	<form action="?page=Client&action=edit&id=<?php echo $id?>&noheader=true" method="post" name="editclient" id="editclient" class="validate" novalidate="novalidate">
		<?php echo $form->formInput($form->getElement('id'));?>
		<table class="form-table">
			<tbody>
				<tr class="form-field form-required">
					<th scope="row">
						<?php echo $form->formLabel($form->getElement('name'));?>
					</th>
					<td>
						<?php echo $form->formInput($form->getElement('name'));?>
						<?php echo $form->errorMsg($form->getElement('name'));?>
					</td>
				</tr>
				<tr class="form-field form-required">
					<th scope="row">
						<?php echo $form->formLabel($form->getElement('email'));?>
					</th>
					<td>
						<?php echo $form->formInput($form->getElement('email'));?>
						<?php echo $form->errorMsg($form->getElement('email'));?>
					</td>
					
				</tr>
				<tr class="form-field">
					<th scope="row">
						<?php echo $form->formLabel($form->getElement('fone'));?>
					</th>
					<td>
						<?php echo $form->formInput($form->getElement('fone'));?>
						<?php echo $form->errorMsg($form->getElement('fone'));?>
					</td>

				</tr>
			</tbody>
		</table>
	
	
		<p class="submit">
			<input type="submit" name="editClient" id="editClient" class="button button-primary" value="Edit client">
		</p>
	</form>
</div>



